selfdestruct command
verixx/selfbot pull request #125
Opened 2017-11-02 05:09 UTC by PallavBS

2017-11-02 14:07 UTC, fourjr requested changes
What? This isnt just the selfdestruct command!

2017-11-12 15:01 UTC, FloatCobra commented
You're low for trying to change the info.

2017-11-12 15:01 UTC, closed without merging

2017-11-12 15:03 UTC, KorewaKiyo reviewed
fuck off

2017-11-12 15:03 UTC, FloatCobra commented on cogs/info.py
> +        embed.add_field(name='Author', value='Pallav#1747')
Fuck off with this

2017-11-12 15:03 UTC, FloatCobra commented on cogs/info.py
> +        github = '[Click Here](https://github.com/PallavBS/selfbot.py/)'
Fuck off again